sources:
  - name: zkbob-bob-goerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/zkbob/{context.subgraphName:zkbob-bob-goerli}

additionalTypeDefs: |
  extend type DirectDeposit {
    subgraphName: String!
  }

additionalResolvers:
  - ./dd/dd-resolvers

documents:
  - ./dd/dd-query.graphql

codegen:
  contextType: 'MeshContext & { subgraphName: string }'